### ISSUE TITLE
filling getoutput() 

### ISSUE THREAD

**Issue by demousteven** [GoogleCloudPlatform/DataflowJavaSDK#544] opened 2017-02-02 11:27 UTC
how can I fill getoutput() whether it's on bigquery level of or GCS level please these are some of the scenarios:
private static interface Options extends PipelineOptions {
    @Description("Path of the file to write to")
    @Validation.Required
    String getOutput();
    void setOutput(String value);

@Description("Table to write to, specified as "
        + "<project_id>:<dataset_id>.<table_id>. "
        + "The dataset_id must already exist")
    @Validation.Required
    String getOutput();
    void setOutput(String value);

i am getting errors thanks

**Comment by davorbonaci** [comment] 2017-03-06 18:21
Sounds like a duplicate of #545; closing.

**Closed by davorbonaci** 2017-03-06 18:21 UTC
